Document the import spreadsheet
nationalarchives/ds-find-caselaw-docs pull request #172
Opened 2024-07-09 16:52 UTC by dragon-dxw

2024-07-19 13:09 UTC, dragon-dxw commented
Discussion in standup: should also check is published. Log those that are not published.

2024-08-01 13:01 UTC, jlhdxw approved these changes
LGTM, some minor comments that may not be an issue

2024-08-01 13:01 UTC, jlhdxw commented on utilities/spreadsheet_docx/copy_from_bailii_s3.py
> +    row_object = Row(**dict(zip(headers, row)))
I'm not sure on the data here (assuming it's generated by the user of this script) but is it possible rows don't have all the data? We could check here first with `if len(row) == len(headers): ...` to ensure they have all the columns

2024-08-01 14:48 UTC, jacksonj04 requested changes
Couple of immediate comments, now going through in depth

2024-08-01 14:48 UTC, jacksonj04 commented on utilities/spreadsheet_docx/copy_from_bailii_s3.py
> +with Path.open(SPREADSHEET) as f:
This raises the following with mypy:

```
No overload variant of "open" of "Path" matches argument type "str"
```

I think you want:

```suggestion
with Path(SPREADSHEET).open() as f:
```

2024-08-01 14:48 UTC, jacksonj04 commented on utilities/spreadsheet_docx/copy_from_bailii_s3.py
> +        with Path.open("not_published.jsonl", "a") as f:
Same as `:37`:

```suggestion
        with Path("not_published.jsonl").open("a") as f:
```

2024-08-01 14:48 UTC, jacksonj04 commented on utilities/spreadsheet_docx/copy_from_bailii_s3.py
> +        dryrun_bonus = [DRY_RUN] if DRY_RUN else []
I'm unclear on the logic here, `DRY_RUN` is set to `"--dryrun"` so will always evaluate to `True`, should there be some argument parsing going on?

2024-08-01 16:58 UTC, dragon-dxw commented on utilities/spreadsheet_docx/copy_from_bailii_s3.py
> +        extension_match = re.search(r"^(.*)\.([a-z]*)$", self.filename)
I have checked and the extensions should be exactly the ones on L50. Anything else means we've changed the file. I'm 100% okay with this being terribly, terribly brittle (as long as it explodes safely) since it should only ever be running against one file.

2024-08-01 16:58 UTC, dragon-dxw commented on utilities/spreadsheet_docx/copy_from_bailii_s3.py
> +        response = requests.head(f"{ASSETS_BASE}/{self.target_key()}", timeout=30)
Yes. We're going to be running this manually; I'm personally OK with brittleness over uncertain behaviour.

2024-08-01 16:59 UTC, dragon-dxw commented on utilities/spreadsheet_docx/copy_from_bailii_s3.py
> +        dryrun_bonus = [DRY_RUN] if DRY_RUN else []
I've hard coded it to avoid screwups during development; but yes, argument parsing sounds like a plan.

2024-08-01 17:00 UTC, dragon-dxw commented on utilities/spreadsheet_docx/copy_from_bailii_s3.py
> +    row_object = Row(**dict(zip(headers, row)))
Good shout.

2024-08-27 11:50 UTC, jacksonj04 approved these changes

2024-08-27 13:22 UTC, merged